# Generated by Django 5.0.1 on 2024-01-12 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('count_in_stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Figurine',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_store.items')),
                ('weight', models.FloatField()),
                ('height', models.FloatField()),
                ('width', models.FloatField()),
            ],
            bases=('book_store.items',),
        ),
        migrations.AddField(
            model_name='items',
            name='id_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='book_store.cart'),
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('items', models.ManyToManyField(blank=True, related_name='items', to='book_store.items')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='id_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book_store.customers'),
        ),
        migrations.AddField(
            model_name='items',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='book_store.tags'),
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('items_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='book_store.items')),
                ('date_release', models.DateField()),
                ('authors', models.ManyToManyField(related_name='authors', to='book_store.authors')),
            ],
            bases=('book_store.items',),
        ),
    ]
