# Generated by Django 5.0.1 on 2024-02-08 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('photo', models.ImageField(blank=True, default='photos/default/default.jpg', upload_to='photos/users/Y%/m%/d%', verbose_name='Фото')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователь',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Количество')),
                ('items', models.ManyToManyField(blank=True, related_name='histories', to='goods.item', verbose_name='Покупки')),
                ('id_customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book_store.users', verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('items', models.ManyToManyField(blank=True, related_name='cart', to='goods.item', verbose_name='Покупки')),
                ('id_customer', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book_store.users', verbose_name='Пользователь')),
            ],
        ),
    ]
