# Generated by Django 5.0.1 on 2024-01-22 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0002_users_alter_authors_options_alter_books_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default/default.jpg', upload_to='photos/items/Y%/m%/d%'),
        ),
        migrations.AddField(
            model_name='items',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 1, 22, 11, 39, 1, 356602, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='time_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, default='media/photos/default/default.jpg', upload_to='photos/users/Y%/m%/d%'),
        ),
    ]
