# Generated by Django 5.0.1 on 2024-01-26 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0003_items_photo_items_time_created_items_time_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='books',
            name='authors',
            field=models.ManyToManyField(related_name='authors', to='book_store.authors', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='books',
            name='date_release',
            field=models.DateField(verbose_name='Дата выхода'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='id_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book_store.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='book_store.items', verbose_name='Покупки'),
        ),
        migrations.AlterField(
            model_name='figurine',
            name='height',
            field=models.FloatField(verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='figurine',
            name='weight',
            field=models.FloatField(verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='figurine',
            name='width',
            field=models.FloatField(verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='history',
            name='count',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='history',
            name='id_customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='book_store.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='history',
            name='items',
            field=models.ManyToManyField(blank=True, to='book_store.items', verbose_name='Покупки'),
        ),
        migrations.AlterField(
            model_name='items',
            name='cost',
            field=models.IntegerField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='items',
            name='count_in_stock',
            field=models.IntegerField(verbose_name='Количество в наличии'),
        ),
        migrations.AlterField(
            model_name='items',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default/default.jpg', upload_to='photos/items/Y%/m%/d%', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='items',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='book_store.tags', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='items',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='items',
            name='time_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Время последнего редактирования'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя тега'),
        ),
        migrations.AlterField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default/default.jpg', upload_to='photos/users/Y%/m%/d%', verbose_name='Фото'),
        ),
    ]
