# Generated by Django 5.0.1 on 2024-02-13 13:24

import builtins
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': (builtins.id,), 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователь'},
        ),
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default/default.jpg', upload_to='photos/users/Y%/m%/d%', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))], verbose_name='Фото'),
        ),
    ]
