# Generated by Django 5.0.1 on 2024-02-14 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователь'},
        ),
    ]
