# Generated by Django 5.0.1 on 2024-02-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Товар активен'),
        ),
    ]
