# Generated by Django 5.0.1 on 2024-02-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Завершен'), ('PENDING', 'В процессе'), ('CANCELLED', 'Отменен')], max_length=255),
        ),
    ]
